using System.Collections.Generic;
using System.Linq;
using System.Threading;
/*
 * @CreateTime: May 14, 2019 1:27 PM
 * @Author:  Mikael Araya
 * @Contact: MikaelAraya12@gmail.com
 * @Last Modified By:  Mikael Araya
 * @Last Modified Time: May 14, 2019 2:05 PM
 * @Description: Modify Here, Please 
 */
using System.Threading.Tasks;
using AccountingBackend.Application.AccountTypes.Models;
using AccountingBackend.Application.AccountTypes.Queries.GetAccountType;
using AccountingBackend.Application.AccountTypes.Queries.GetAccountTypeList;
using AccountingBackend.Application.Exceptions;
using Xunit;

namespace AccountingBackend.Application.Test.AccountTypes.Queries.GetAccountTypeList {
    public class GetAccountTypeListQueryHandlerShould : DatabaseTestBase {

        /// <summary>
        /// test the successful return of account types list
        /// </summary>
        /// <returns></returns>
        [Fact]
        public async Task ReturnListOfAccountTypesSuccessFuly () {
            // Arrange
            GetAccountTypeListQuery query = new GetAccountTypeListQuery ();
            GetAccountTypeListQueryHandler handler = new GetAccountTypeListQueryHandler (_Database);
            // Act
            var result = await handler.Handle (query, CancellationToken.None);

            // Assert
            Assert.IsType<List<AccountTypeView>> (result);
            Assert.True ((result as List<AccountTypeView>).Count () > 0);
        }

        /// <summary>
        /// test the return of account type list generated by user only
        /// </summary>
        /// <returns></returns>

        [Fact]
        public async Task ReturnOnlyAccountsListCreatedByUser () {
            GetAccountTypeListQuery query = new GetAccountTypeListQuery ();
            GetAccountTypeListQueryHandler handler = new GetAccountTypeListQueryHandler (_Database);
            // Act
            var result = await handler.Handle (query, CancellationToken.None);

            // Assert
            Assert.False (result.Any (a => a.TypeOfId == 0));
        }

        /// <summary>
        /// tests the return of account type index view only generated by when 
        /// requested
        /// </summary>
        /// <returns></returns>

        [Fact]
        public async Task ReturnUserGeneratedAccountTypeIndexSuccessfuly () {
            GetAccountTypeIndexQuery query = new GetAccountTypeIndexQuery () {
                Main = false
            };
            GetAccountTypeIndexQueryHandler handler = new GetAccountTypeIndexQueryHandler (_Database);
            // Act
            var result = await handler.Handle (query, CancellationToken.None);

            // Assert
            Assert.False (result.Any (a => a.TypeOf == 0));
        }

        /// <summary>
        /// tests return of system generate account types only when requested
        /// </summary>
        /// <returns></returns>
        [Fact]
        public async Task ReturnSystemAccountTypeIndexSuccessfuly () {
            GetAccountTypeIndexQuery query = new GetAccountTypeIndexQuery () {
                Main = true
            };
            GetAccountTypeIndexQueryHandler handler = new GetAccountTypeIndexQueryHandler (_Database);
            // Act
            var result = await handler.Handle (query, CancellationToken.None);

            // Assert
            Assert.False (result.Any (a => a.TypeOf != 0));

        }

        /// <summary>
        /// tests the return of single account type instance when provided a valid account type id
        /// </summary>
        /// <returns></returns>
        [Fact]
        public async Task ReturnSingleInstanceOfAccountTypeSuccessfuly () {
            GetAccountTypeQuery query = new GetAccountTypeQuery () {
                Id = 6
            };
            GetAccountTypeQueryHandler handler = new GetAccountTypeQueryHandler (_Database);
            // Act
            var result = await handler.Handle (query, CancellationToken.None);
            // Assert
            Assert.Equal (6u, result.Id);
        }

        /// <summary>
        /// tests the return of not found exception when requested for account type id that does not 
        /// exist
        /// </summary>
        [Fact]
        public async Task ThrowNotFoundExceptionWhenIdDoesNotExists () {
            GetAccountTypeQuery query = new GetAccountTypeQuery () {
                Id = 100
            };
            GetAccountTypeQueryHandler handler = new GetAccountTypeQueryHandler (_Database);
            // Act
            await Assert.ThrowsAsync<NotFoundException> (() => handler.Handle (query, CancellationToken.None));
        }

        /// <summary>
        /// tests the return of not found exception when requested for system generated account type
        /// </summary>
        /// <returns></returns>
        [Fact]
        public async Task ThrowNotFoundExceptionWhenRequestedForSystemGeneratedType () {
            GetAccountTypeQuery query = new GetAccountTypeQuery () {
                Id = 1
            };
            GetAccountTypeQueryHandler handler = new GetAccountTypeQueryHandler (_Database);
            // Act
            await Assert.ThrowsAsync<NotFoundException> (() => handler.Handle (query, CancellationToken.None));
        }

    }
}